### ISSUE TITLE
4주차 개발 계획

### ISSUE THREAD

**Issue by roomedia** [roomedia/dakku#15]
### 개발 현황
* DB에 다이어리 저장
* 저장된 다이어리 목록으로 표시, 북마크, 잠금
* 텍스트 스티커 생성

### 4주차 개발 계획
- [x] 프로젝트 구조 수정 #16
- [x] 텍스트 스티커 저장 #17
- [x] 다이어리 선택 시 해당 다이어리에 저장된 스티커 불러오기 #17
- [x] 텍스트 스티커 업데이트 #17

### 수정 사항
* 데이터베이스 초기 데이터 입력 실패 #19
* 다이어리 생성 후 저장 시 duplicate 되는 버그 #20 
* 에디터 테마 디자인에 맞게 변경 #21 
* 다이어리 조회 시 스타일이 적용되지 않는 버그 #24

### 도전 과제
- [x] 텍스트 수정 시 키보드 자동 열기 #18
- [ ] 다이어리 저장 시 썸네일 사이즈(128dp x 192dp) 이미지로 출력
- [ ] 다이어리 목록에서 저장된 썸네일과 해당 다이어리 연동
- [ ] 텍스트 스티커 이동, 회전, 크기 조정
- [ ] 이미지 스티커 추가

**Comment by roomedia** [comment]
### 4주차 회고
급하게 개발하다보니 의도치 않은 버그가 발생하여 시간을 잡아먹었다. 테스트를 철저히 하도록 하자.
