### ISSUE TITLE
5주차 개발 계획

### ISSUE THREAD

**Issue by roomedia** [roomedia/dakku#27]
### 개발 현황
* DB에 다이어리 저장
* 저장된 다이어리 목록으로 표시, 북마크, 잠금
* 텍스트 스티커 생성, 저장, 조회, 수정

### 5주차 개발 계획
- [x] 다이어리 썸네일로 저장, 조회 #28
- [x] 이미지 스티커 생성, 저장, 조회, 수정 #29
- [x] 스티커 선택, 이동, 회전, 크기 조정 제스처 #30
- [x] 선택된 스티커 삭제 버튼 [828be26](https://github.com/roomedia/dakku/pull/29/commits/828be26145daadf746db8be1cbc3b522881e3afa) #29
- [ ] 유저 예상 결과물 생성

### 도전 과제
* undo, redo 버튼
* 선택된 스티커 복제 버튼
* 스티커 레이어 조정 버튼

**Comment by roomedia** [comment]
특정 상황에서 이미지 flickering 되는 버그 있었음. 재현 필요.

**Comment by roomedia** [comment]
### 5주차 회고
다음 주차에는 텍스트, 이미지 속성을 집중 구현하여 "즉시 적용할 수 있는 템플릿"을 생성할 수 있도록 노력하자.
