### ISSUE TITLE
7주차 개발 계획

### ISSUE THREAD

**Issue by roomedia** [roomedia/dakku#33]
### 개발 현황
* DB에 다이어리, 텍스트 스티커, 이미지 스티커 저장
* 저장된 다이어리를 목록으로 표시, 북마크 및 잠금 기능 제공 (비밀번호 변경 불가)
* 텍스트 스티커 이동, 회전, 속성 변경 구현
* 이미지 스티커 이동, 회전, 크기 조정 구현 (이미지 마스킹, 리사이징 구현 필요)

### 7주차 개발 계획
- [x] 클릭/드래그 이벤트 중첩 시 클릭만 적용되는 버그 해결 #34
- [x] 특정 버튼 클릭 시에만 UI가 노출되도록 변경 #36 
- [x] 레이어 조정 버튼 구현 #37
- [x] 텍스트 스티커 폰트 선택 #4 #32
- [x] 애플리케이션 설치 시 스티커 프리셋 다운로드 #35
- [x] 필수 기능만 포함하여 출시 #39
